version: '3'

services: 
    app:
        container_name: app_node
        build: 
            context: ./node
            dockerfile: Dockerfile.prod
        networks: 
            - app-network
        volumes:
            - ./node:/usr/src/app

    db:
        image: mysql:5.7
        command: --innodb-use-native-aio=0
        container_name: mysql
        restart: always
        tty: true
        volumes: 
            - ./mysql:/var/lib/mysql
        environment: 
                - MYSQL_DATABASE=db_desafio_nginx_node
                - MYSQL_ROOT_PASSWORD=102030
        networks: 
            - app-network
        ports: 
            - 3306:3306

    nginx:
        container_name: nginx
        image: nginx:1.15-alpine
        tty: true
        volumes:
            - "./node:/node"
            - "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
            - "./nginx/logs:/var/log/nginx"
        networks: 
            - app-network
        ports: 
            - "8080:80"
        
networks: 
    app-network:
        driver: bridge